# Generated by Django 2.1 on 2018-08-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180821_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
