# Generated by Django 2.1 on 2018-08-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180822_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='country',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
